### ISSUE TITLE
Some columns aren't displayed in the occurence table view

### ISSUE THREAD

**Issue by giannijacot** [gbif/hp-swiss-bif#2]
Hello, 

I've added some new columns in the table view for occurrences in the config.js file and some of them aren't displayed in the column selection menu and the table (see [https://swiss-bif.hp.gbif-staging.org/en/occurrence/search?view=TABLE](https://swiss-bif.hp.gbif-staging.org/en/occurrence/search?view=TABLE)).

The columns which aren't showing are higherGeography, stateProvince, establishmentMeans, iucnRedListCategory and datasetName.

Do you know if these columns doesn't show because they are not supported by the hosted portal or are if there are other reasons ?

The higherGeography and establishmentMeans doesn't have value in them for our occurrences so it maybe reason why they doesn't show.

**Comment by MortenHofft** [comment]
https://hp-theme.gbif-staging.org/data-exploration-config#default-columns-in-occurrence-table
They are not supported. I can add them. I've been cautious adding columns as it means transferring more data for everyone with the current implementation
