### ISSUE TITLE
Custom map colors

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-swiss-bif#4]
> We are starting to look at the style customization possibilities of our SwissBIF portal and we were wondering if it’s possible to select other colors for the points on the map in the same way as the [map api](https://techdocs.gbif.org/en/openapi/v2/maps).

Yes that is possible, add this to the theme https://github.com/gbif/hp-swiss-bif/blob/master/_includes/js/config.js#L8
`mapDensityColors: ['#051937', '#004d7a', '#008793', '#00bf72', '#a8eb12'] // have to be 5 colours`

**Comment by giannijacot** [comment]
Thanks, it was exactly what we were looking for ! We will make some tests to see if some colors can be nice with our theme.
