### ISSUE TITLE
Custom style for the points on the map

### ISSUE THREAD

**Issue by giannijacot** [gbif/hp-swiss-bif#5]
Like for the color change of the points on the map we are interested in changing the style of the points. We would like to use the hexagon like in [this exemple](https://api.gbif.org/v2/map/demo2.html#map=6/1106029.46/5705864.45/0) and maybe other styles that are available on the maps on gbif.org on the dataset page for exemple :

![image](https://github.com/gbif/hp-swiss-bif/assets/99412754/69c64973-84dd-4621-9983-136ccbbfc037)

Is there a way to change the style of the points in the configuration ?

**Comment by MortenHofft** [comment]
No, there is not. We are not using server side rendered tiles as in your example above. You are welcome to leave a feature request in https://github.com/gbif/hosted-portals/issues

Those map that you refer to are all preprocessed to a higher resolution than what we can do with maps that are generated on the fly as users enter an arbitrary filter

**Comment by giannijacot** [comment]
Thanks for your answer and for the explanation. The goal was just to test the rendering, but we'll think about whether we really want to have this feature and leave an issue if needed.
