### ISSUE TITLE
Adding higherGeography in the selectable charts for dashboards

### ISSUE THREAD

**Issue by giannijacot** [gbif/hp-swiss-bif#6]
I recently tested adding dashboards in pages of the hosted portal and I saw that we can't add a chart to aggregate data by higherGeography. Would it be possible to make this field available for charts in dashboards ?

It would be useful for us to be able to add charts with this field to help users understand our data.

**Comment by MortenHofft** [comment]
Yes, we can add that I would think. But have you considered using admin gadm regions instead? They are normalized across datasets and inferred from coordinates

**Comment by tschudip** [comment]
Thank you very much Morten. (1) Swiss biogeographical entities (https://www.geocat.ch/geonetwork/srv/fre/catalog.search#/metadata/fc110d43-cfbc-4029-a73c-f24bd67c9689) are not on gadm.org: We identify the corresponding region for all records with sufficient spatial resolution, based on source coordinates, and share this information via higherGeographyID. (2) Regarding administrative entities: To be shared conformingly with the currently agreed national ethical framework, a significant part of our data is gridded. This may result in a divergence of the administrative entity inferred from coordinates with respect to the original record. We wish to use stateProvince to confirm the effective administrative entity (related to the original spatial reference). As soon as implemented, this will transparently be declared under dataGeneralizations. With this procedure (1 and 2), users can always generate reliable species lists per Swiss biogeographical (sub-)region and/or canton. This is particularly helpful for smaller cantons (eg Geneva or Basel-Stadt), but also of interest for cantons with partial overlaps with biogeographical (sub-)regions. Dashboards will simplify the access to this information.

**Comment by MortenHofft** [comment]
There is now a higher geography breakdown, but since it is a free text multi value field it is hard to do much with in terms of presentation.

**Comment by tschudip** [comment]
- works great, corresponds exactly to our ideas, thank you!

**Comment by giannijacot** [comment]
It works when adding a new dashboard in the occurence dashboard view but when adding dashboard in markdown pages of the hosted portal it doesn't seem to work (see the [last commit](https://github.com/gbif/hp-swiss-bif/commit/15918e3550075e6eceae1e9dc9bbf72e4d3a0abf) of the repo). It would also be useful for us if we could add it in dashboards in markdown pages.

Is it two separate things?

**Comment by MortenHofft** [comment]
Yes it is, sorry. I created the chart and added an option for it in occurrence search dashboards. I hade not added it for markdown use. I've done that as well now.

**Comment by giannijacot** [comment]
Thanks !
